version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "daily"
      time: "00:00"
